name: app_delivery
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Ajustado para ser más compatible

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_auth: ^4.15.3
  firebase_database: ^10.3.8
  intl: ^0.19.0
  url_launcher: ^6.2.2

  # Reemplazamos Google Maps por OpenStreetMap
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

  # Mantener estas dependencias para geolocalización
  geolocator: ^10.1.0
  permission_handler: ^11.1.0
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^18.0.1
  googleapis_auth: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
